In [1]:
import numpy as np

## Numpy 버전 확인

In [2]:
np.__version__

'1.16.4'

## 넘파이 배열 만들기

- np.array(리스트)
- 숫자, 문자로 아이템 삽입

In [3]:
# 숫자 넘파이 배열 생성하기 
n1 = np.array([1,5,6,10,33])
n2 = np.array([0.5,2.0,5,45.4])
n1
n2
print(n1)
print(n2)

[ 1  5  6 10 33]
[ 0.5  2.   5.  45.4]


In [4]:
# 문자 넘파이 배열 만들기 
color_list = np.array(['빨강','파랑','초록'])
color_list
print(color_list.size, len(color_list), 
      color_list.shape)

3 3 (3,)


In [5]:
# 한개의 넘파이 배열 출력시에는 for 반복문 이용 
for i in color_list:
    print(i)

빨강
파랑
초록


## 넘파이 배열 인덱싱

- 넘파이배열변수[indexNumber]

In [6]:
n1

array([ 1,  5,  6, 10, 33])

In [7]:
n1[0]

1

In [8]:
n1[4]

33

In [9]:
n1[-1]

33

In [10]:
# 2번 인덱스 부터 추출 
n1[2:]

array([ 6, 10, 33])

In [11]:
n1[:]

array([ 1,  5,  6, 10, 33])

## 퀴즈

- animal 이라는 넘파이 배열 생성 
- 구성요소는 동물 이름 
  [호랑이, 토끼, 곰, 거북이, 펭귄]
- 역순으로 하나씩 출력
  [펭귄 거북이 곰 토끼 호랑이]

In [12]:
animal = np.array(['호랑이', '토끼', '곰', '거북이', '펭귄'])
animal

array(['호랑이', '토끼', '곰', '거북이', '펭귄'], dtype='<U3')

In [13]:
for i in range(5):
    print(i)

0
1
2
3
4


In [14]:
# range(초기,끝,증감치)
for i in range(5,0,-1):
    print(i)

5
4
3
2
1


In [15]:
for i in animal:
    print(i)

호랑이
토끼
곰
거북이
펭귄


In [16]:
# 역순 
n = len(animal)
for n in range(n-1,-1,-1):
    print(animal[n])

펭귄
거북이
곰
토끼
호랑이


## 넘파이 배열의 속성 알아보기

- 넘파이배열변수.shape : 구조와 크기
- type(넘파이배열변수) : 객체의 형태 출력
- 넘파이배열변수.ndim : 차원
- 넘파이배열변수.dtype : 데이터형

In [17]:
# 정수, 실수, 문자열 넘파이 생성 
np1 = np.array(['세종대','건국대','연세대'])
np2 = np.array([3,4,5,10])
np3 = np.array([1.4, 5.0])
print(np1, np2, np3)

['세종대' '건국대' '연세대'] [ 3  4  5 10] [1.4 5. ]


In [18]:
print(np1, type(np1))

['세종대' '건국대' '연세대'] <class 'numpy.ndarray'>


In [19]:
myList = ['세종대' '건국대' '연세대']
type(myList)

list

In [20]:
# .shape 넘파이 배열의 크기와 구조 
np1.shape

(3,)

In [21]:
len(np1)

3

In [22]:
# .ndim : 차원 확인 
np1.ndim

1

In [23]:
# .dtype : 배열의 데이타형 확인하기 
print(np1.dtype, np2.dtype, np3.dtype)

<U3 int64 float64


## 자동 데이터 형 변환

- 숫자 + 문자 -> 문자
- 정수형 + 실수형 -> 실수형

In [24]:
print(np1, np1.dtype)

['세종대' '건국대' '연세대'] <U3


In [25]:
print(np3, np3.dtype)

[1.4 5. ] float64


In [26]:
np4 = np.array(['세종대','이화여대',34, 6.7])
np4

array(['세종대', '이화여대', '34', '6.7'], dtype='<U4')

In [27]:
np4.dtype

dtype('<U4')

In [28]:
np5 = np.array([4, 5, 5.5])
np5

array([4. , 5. , 5.5])

In [29]:
np5.dtype

dtype('float64')

## 데이터 형 변환하기 - Casting

- 새넘파이배열변수 = 넘파이배열이름.astype(데이터형)
- 데이터형 : float, int, '<U2', np.str

In [30]:
# 정수형 넘파이 배열 
a = np.array([1,2,36,10])
print(a, a.dtype)

[ 1  2 36 10] int64


In [31]:
# 정수형 -> 문자형 넘파이 배열 
# b = a.astype('<U2')
b = a.astype(np.str)
print(b, b.dtype)

['1' '2' '36' '10'] <U21


In [32]:
# 정수형 ->  실수형 넘파이 배열 
c = a.astype(float)
print(c, c.dtype)

[ 1.  2. 36. 10.] float64


In [33]:
num = 32434234234234234234
print(num, type(num))

32434234234234234234 <class 'int'>


## 넘파이 배열 생성시 자료형 지정하기

- np.array(데이타리스트, dtype=데이타자료형)
- 데이터형 : float, int, '<U2', np.str

In [34]:
# 정수형 -> 문자형 
aa = np.array([3, 10, 33, 20],dtype=np.str)
print(aa, aa.dtype)

['3' '10' '33' '20'] <U2


In [35]:
# 실수형 -> 정수형 
# 소숫점 아래 자리는 자동으로 삭제된다. 
bb = np.array([3.45, 5.5, 45.1],dtype=int)
print(bb, bb.dtype)

[ 3  5 45] int64


## 2차원 배열 만들기

- 넘파이배열변수 = np.array([[1행...],[2행...]])
- 각 행의 데이타 갯수가 같아야 한다.

In [36]:
np2d = np.array([[3,4,5],[6,7,8]])
np2d 

array([[3, 4, 5],
       [6, 7, 8]])

In [37]:
# 넘파이배열의 형태 확인 
np2d.shape

(2, 3)

In [38]:
# 전체 넘파이 배열의 갯수 출력 
# len(np2d)
np2d.size

6

In [39]:
# 전체 차원수 확인하기 
np2d.ndim

2

## 퀴즈

- 2행 3열의 넘파이 배열을 생성하여라 - int 형 
- 2행 3열의 넘파이 배열의 데이타형을 문자형으로 변경하여라 - np.str

In [40]:
cc = np.array([[3,4,5],[10,20,20]])
cc.dtype

dtype('int64')

In [41]:
cc_str = cc.astype(np.str)
cc_str

array([['3', '4', '5'],
       ['10', '20', '20']], dtype='<U21')

## 2차원 넘파이 배열 생성 후 하나씩 출력하여라

In [42]:
np2d_list = np.array([[0,45],[20,30]])
np2d_list

array([[ 0, 45],
       [20, 30]])

In [43]:
# 행으로 출력 
for i in np2d_list:
    print(i)

[ 0 45]
[20 30]


In [44]:
# 각각의 원소 출력 
for i in np2d_list:
    print('---------')
    for j in i:
        print(j)

---------
0
45
---------
20
30


In [45]:
# 각각의 가로로 원소 출력 
for i in np2d_list:
    print('\n---------')
    for j in i:
        print(j, end='  ')


---------
0  45  
---------
20  30  

## 0또는 1로 데이터 입력해서 넘파이 배열 만들기

- np.zeros(데이타갯수) : 1차
- np.zeros((행수,열수)) : 2차
- np.ones(데이타갯수) : 1차
- np.ones((행수,열수)) : 2차

In [46]:
np1 = np.zeros(5)
np1

array([0., 0., 0., 0., 0.])

In [47]:
np2 = np.zeros((2,2))
np2

array([[0., 0.],
       [0., 0.]])

In [48]:
np3 = np.ones(5)
np4 = np.ones((3,3))
print(np3,'\n\n', np4)

[1. 1. 1. 1. 1.] 

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 자동으로 숫자 데이터 채워 넘파이 배열 만들기

- np.arange(숫자)
- np.arange(start, end-1)
- np.arange(start, end-1, step)

In [49]:
n1 = np.arange(5)
n1

array([0, 1, 2, 3, 4])

In [50]:
n2 = np.arange(1,8)
n2

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
n3 = np.arange(1,10,2)
n3

array([1, 3, 5, 7, 9])

## 넘파이 배열 구조 변경하기 1

- 1차원 -> 2차원 배열로 변경
- 넘파이배열변수.reshape(행수,열수)

In [52]:
a = np.array([3, 10, 40, 100])
a

array([  3,  10,  40, 100])

In [53]:
a.reshape(2,2)

array([[  3,  10],
       [ 40, 100]])

## 퀴즈

- 1~15로 데이터값을 갖는 넘파이 배열 3행 5열로 생성하여라

```python
[[1,2,3,4,5],
 [6,7,8,9,10],
 [11,12,13,14,15]]
```

In [54]:
result = np.arange(1,16)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
result.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## 넘파이 배열 구조 변경하기 2

- 2차원 -> 1차원 배열로 변경
- 넘파이배열변수.flatten()

In [56]:
cc = np.array([['a','b'],['c','d']])
cc

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [57]:
cc_result = cc.flatten()
cc_result

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [58]:
sum_value = 0
for i in range(1, 101):
    sum_value += i
print(sum_value)

5050


In [59]:
print(np.sum([x for x in range(1, 101)]))

5050


In [60]:
large_arr = np.random.randn(50) 
n = int(len(large_arr)*0.05)
np.sort(large_arr)[::-1][0:n]

array([1.91499795, 1.41358956])

## 넘파이 배열의 연산

- 덧셈
- 뺄셈
- 곱셈

In [61]:
x = np.array([[1,2],[3,4]])
y = np.array([[10,2],[34,10]])

In [62]:
print(x, '\n\n', y)

[[1 2]
 [3 4]] 

 [[10  2]
 [34 10]]


In [63]:
x + y

array([[11,  4],
       [37, 14]])

In [64]:
x - y

array([[ -9,   0],
       [-31,  -6]])

In [65]:
# 수학시간의 행열 연산이 아니고 같은 위치의 데이타가 곱해진다.
x * y

array([[ 10,   4],
       [102,  40]])

In [66]:
x*5

array([[ 5, 10],
       [15, 20]])

In [67]:
x/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [68]:
x ** 2

array([[ 1,  4],
       [ 9, 16]])

## 넘파이 배열의 데이타 교체

In [69]:
subject = np.array(['국어','영어', '수학', '과학'])
subject

array(['국어', '영어', '수학', '과학'], dtype='<U2')

In [70]:
# 0 번째 데이타 교체 
subject[0] = '코딩'
subject

array(['코딩', '영어', '수학', '과학'], dtype='<U2')

## 퀴즈

- 10, 20 ~ 100 까지 10개로 구성된 넘파이 배열을 생성한다. 
- 인덱스가 2~5까지 구성되어 있는 데이타값을 0으로 교체한다. 

```python
[ 10, 20, 30, 40 ... 100]
->
[ 10, 20, 0, 0, 0, 0, 70, 80, 90, 100]
```

In [71]:
q = np.arange(10, 101, 10)
q

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [72]:
q[2:6]= 0
q

array([ 10,  20,   0,   0,   0,   0,  70,  80,  90, 100])

## :: 를 이용한 인덱싱

- 넘파이배열변수[start:end+1:step]

In [73]:
z = np.arange(1,11)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
# 0~2 번 인덱스까지 추출 
z[0:3]

array([1, 2, 3])

In [75]:
# 홀수번째 출력 
z[0:10:2]

array([1, 3, 5, 7, 9])

In [76]:
# 특정 인덱스 출력 
z[0:10:3]

array([ 1,  4,  7, 10])

In [77]:
z[::2]

array([1, 3, 5, 7, 9])

## 2차원 넘파이 인덱싱

In [78]:
arr1 = np.arange(15)
arr1 = arr1.reshape(3,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
# 1행만 추출하기 
arr1[0]

array([0, 1, 2, 3, 4])

In [80]:
arr1[0, :]

array([0, 1, 2, 3, 4])

In [81]:
# 1열만 추출하기 
arr1[:, 0]

array([ 0,  5, 10])

In [82]:
# 홀수번째 행만 추출하기 
arr1[::2,:]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [83]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [84]:
# 홀수번째 열로 구성된 데이타 추출 
arr1[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [85]:
# 마지막 행의 마지막 열 인덱스 
arr1[-1,-1]

14

In [86]:
arr1[0:2,0:2]

array([[0, 1],
       [5, 6]])

In [87]:
arr1[0:2,2:4]

array([[2, 3],
       [7, 8]])

## 난수 생성하기

- np.random.randn(데이터갯수) : 1차원 실수형
- np.random.randn(행수,열수) : 2차원 실수형
- np.random.randint(숫자) : 0~숫자까지의 양수.
- np.random.randint(start, end) : start숫자 ~ end-1숫자까지의 정수

In [88]:
r1 = np.random.randn(10)
r1

array([ 1.118293  ,  1.51581812, -1.80479876, -0.56638744, -1.9117299 ,
       -0.11015668,  1.87941769,  0.63182133, -1.69043737,  0.92193627])

In [89]:
r2 = np.random.randn(4,4)
r2

array([[-0.10482758,  0.6716351 ,  1.4007005 , -0.67061934],
       [ 0.32304915, -2.48815904,  1.23399144,  0.18998695],
       [-0.76281639, -1.52838724,  0.28417408, -1.20681178],
       [ 0.54440362, -0.4595634 ,  1.39577761,  1.5038048 ]])

In [90]:
# 0 ~ 9 사이의 정수 난수 1개 추출 
r3 = np.random.randint(10)
r3

5

In [91]:
r3 = np.random.randint(-20,20)
r3

-20

## 합계와 평균

- 넘파이배열변수.sum()
- 넘파이배열변수.mean()

In [92]:
n1 = np.arange(1,11)
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
n1.sum()

55

In [94]:
n1.mean()

5.5

## 2차원 넘파이 배열의 합

- 넘파이배열변수.sum(axis=0) : 각 열의 합
- 넘파이배열변수.sum(axis=1) : 각 행의 합
- 넘파이배열변수.mean(axis=0) : 각 열의 평균
- 넘파이배열변수.mean(axis=1) : 각 행의 평균

In [95]:
n2 = np.arange(1,13)
n2 = n2.reshape(3,4)
n2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
# 각 열의 합
n2.sum(axis=0)

array([15, 18, 21, 24])

In [97]:
# 각 행의 합
n2.sum(axis=1)

array([10, 26, 42])

In [98]:
# 각 열의 평균
n2.mean(axis=0)

array([5., 6., 7., 8.])

In [99]:
# 각 행의 평균
n2.mean(axis=1)

array([ 2.5,  6.5, 10.5])

## 두 넘파이 배열에서 크거나 작은 숫자만 추출하기

- np.maximum(배열1,배열2)
- np.minimum(배열1,배열2)

In [100]:
x = np.arange(1,5)
y = np.arange(4,8)
print(x, '\n\n', y)

[1 2 3 4] 

 [4 5 6 7]


In [101]:
np.maximum(x,y)

array([4, 5, 6, 7])

In [102]:
# 난수 배열 생성하기 
x1 = np.random.randn(10)
y1 = np.random.randn(10)
print(x1, '\n\n', y1)

[ 0.41126299 -0.92606801  1.25893468  1.05251726 -1.17742771  0.72405583
 -1.00085004  0.21778291 -1.01951649 -0.42228015] 

 [-0.14715097 -0.459645    0.54565385  0.04138905  0.7609047  -1.08482534
  0.95135852 -1.03017727  0.18149208 -0.56723149]


In [103]:
np.maximum(x1,y1)

array([ 0.41126299, -0.459645  ,  1.25893468,  1.05251726,  0.7609047 ,
        0.72405583,  0.95135852,  0.21778291,  0.18149208, -0.42228015])

In [104]:
np.minimum(x1,y1)

array([-0.14715097, -0.92606801,  0.54565385,  0.04138905, -1.17742771,
       -1.08482534, -1.00085004, -1.03017727, -1.01951649, -0.56723149])

## Numpy 배열의 병합( concatenate)

- np.vstack((배열명1,배열명2)) : 행으로 합치기, (( ))에 유의
- np.hstack((배열명1,배열명2)) : 열로 합치기, (( ))에 유의

In [105]:
d = np.arange(1,11)
e = np.arange(11,21)
print(d)
print(e)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [106]:
arr1 = np.vstack((d,e))
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [107]:
# 2차원으로 생성 
arr1.shape

(2, 10)

In [108]:
arr2 = np.hstack((d,e))
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [109]:
# 1차로 생성 
arr2.shape

(20,)

## 정렬과 관련된 함수 이용하기

- np.sort(배열이름) : 오름차순 정렬
- np.sort(배열이름)[::-1] : 내림차순 정렬, 역정렬

In [110]:
r1 = np.random.randn(10)
r1

array([ 0.42892337,  1.54225027,  0.29841137,  0.51561446,  0.36325819,
       -0.26213702, -1.33751269,  1.23000273, -0.95048996, -0.4404858 ])

In [111]:
# 오름차순 
np.sort(r1)

array([-1.33751269, -0.95048996, -0.4404858 , -0.26213702,  0.29841137,
        0.36325819,  0.42892337,  0.51561446,  1.23000273,  1.54225027])

In [112]:
# 내림차순 
np.sort(r1)[::-1]

array([ 1.54225027,  1.23000273,  0.51561446,  0.42892337,  0.36325819,
        0.29841137, -0.26213702, -0.4404858 , -0.95048996, -1.33751269])

## 정렬과 관련된 함수 이용하기 – 2차원

- np.sort(배열이름, axis=0) – 열방향으로 정렬하기
- np.sort(배열이름, axis=0)[::-1] – 열방향으로 정렬하기
- np.sort(배열이름, axis=1) – 행방향으로 정렬하기
- np.sort(배열이름, axis=1)[::-1] – 행방향으로 정렬하기

In [113]:
r2 = np.random.randn(3,4)
r2

array([[ 0.91301486,  0.89582051, -1.25430899, -0.99326456],
       [ 0.48726725, -0.67828809,  2.35029784,  0.62759027],
       [ 0.78759616,  0.23413078,  0.69903768, -2.12724832]])

In [114]:
np.sort(r2, axis=0)

array([[ 0.48726725, -0.67828809, -1.25430899, -2.12724832],
       [ 0.78759616,  0.23413078,  0.69903768, -0.99326456],
       [ 0.91301486,  0.89582051,  2.35029784,  0.62759027]])

In [115]:
np.sort(r2, axis=1)

array([[-1.25430899, -0.99326456,  0.89582051,  0.91301486],
       [-0.67828809,  0.48726725,  0.62759027,  2.35029784],
       [-2.12724832,  0.23413078,  0.69903768,  0.78759616]])

## 중복값 제거하기

- np.unique(배열명)

In [116]:
# 중복 데이타가 있는 넘파이 배열 생성 
kk = np.array(['철수','영희','철수','길동','지민','지민','지민'])
kk

array(['철수', '영희', '철수', '길동', '지민', '지민', '지민'], dtype='<U2')

In [117]:
kk_result = np.unique(kk)
kk_result

array(['길동', '영희', '지민', '철수'], dtype='<U2')

## 단위행렬(Identity) : 대각선이 1인 행렬

- np.identity(대각선숫자)
- np.identity(n=대각선숫자, dtype=데이타형)

In [118]:
# 실수형 단위행렬 
g_arr = np.identity(3)
g_arr 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
# 정수형 단위 행렬 
v_arr = np.identity(5, dtype=int)
v_arr 

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [120]:
v_arr.dtype

dtype('int64')

## Numpy 배열의 Boolean Indexing

- 다수개의 배열에서 특정 값을 추출할 때 사용한다.
- 배열이름[조건]

In [121]:
# 조건이 되는 배열의 전체 갯수가 조건을 적용할 배열의 행수와 같아야 한다. 
data = np.random.randn(7,4)
names = np.array(['Charles','Jhon', 'Hayoung','Charles',
                  'Hayoung','Jhon','Elise'])
data

array([[-1.93995453, -0.79060419, -0.46065434, -0.75212797],
       [ 1.01802252,  0.2082336 ,  1.21078623,  1.45268108],
       [ 0.13133058, -1.60820371,  1.64496614,  1.34380878],
       [-0.57456934,  1.58560549,  0.82307981,  0.73870598],
       [ 1.95156487,  2.32511336,  2.40293254, -0.03096243],
       [-3.06139582, -0.16311652,  1.85730434,  1.19174458],
       [ 0.06624817,  1.37345606, -1.22338354,  0.24017442]])

In [122]:
names

array(['Charles', 'Jhon', 'Hayoung', 'Charles', 'Hayoung', 'Jhon',
       'Elise'], dtype='<U7')

In [123]:
# == , != : True / False
# names 넘파이 배열에서 'Hayoung' 값과 같으면 True 를 출력 
names == 'Hayoung'

array([False, False,  True, False,  True, False, False])

In [124]:
# 인덱스 2, 4번이 추출 
data[names == 'Hayoung']

array([[ 0.13133058, -1.60820371,  1.64496614,  1.34380878],
       [ 1.95156487,  2.32511336,  2.40293254, -0.03096243]])

In [125]:
names == 'Elise'

array([False, False, False, False, False, False,  True])

In [126]:
data[names == 'Elise']

array([[ 0.06624817,  1.37345606, -1.22338354,  0.24017442]])

In [127]:
# 마지막 행 제외 나머지 행 추출 
data[names != 'Elise']

array([[-1.93995453, -0.79060419, -0.46065434, -0.75212797],
       [ 1.01802252,  0.2082336 ,  1.21078623,  1.45268108],
       [ 0.13133058, -1.60820371,  1.64496614,  1.34380878],
       [-0.57456934,  1.58560549,  0.82307981,  0.73870598],
       [ 1.95156487,  2.32511336,  2.40293254, -0.03096243],
       [-3.06139582, -0.16311652,  1.85730434,  1.19174458]])

# Numpy 파일 로딩과 저장

## 현재 작업폴더 확인하기

In [128]:
import os

In [129]:
os.getcwd()

'/home/parksangwoo/Repository/Data-Practices/code'

## 넘파이에서 파일 로딩

np.loadtxt('파일경로', delimiter='구분자', dtype=데이터형)

In [130]:
data = np.loadtxt('../data/movielens-1m/ratings.dat', delimiter='::', dtype=int)
# 데이타 구조 확인
data.shape

(1000209, 4)

In [131]:
# 5개만 추출 
# data[:5, :]
data[:5]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]])

In [132]:
# 2열 추출
data[:,2].shape

(1000209,)

In [133]:
# 평균 구하기
data_mean = data[:,2].mean()
data_mean

3.581564453029317

In [134]:
# 소숫점 2째자리까지만 출력하기
print('평균 : %.2f' % data_mean)

평균 : 3.58


## 텍스트 파일로 저장하기

np.savetxt(fileURL, dataVar, fmt=format형식(%.3f)', delimiter=구분자)

In [135]:
## 외부 파일 저장하기
data2 = data[:10]
data2

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368]])

In [136]:
np.savetxt("../output/ratings_data.csv", data2, fmt='%.3f', delimiter=",")